# Generated by Django 6.0.3 on 2026-03-13 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='total_distance_km',
            new_name='total_distance_mi',
        ),
    ]
